Добавлен лог при ошибке генерации отчета
srclab/statistics-reports pull request #1
Opened 2022-03-15 11:00 UTC by M9snikFeed

https://app.asana.com/0/1201909510841246/1201949042034404/f

2022-03-15 11:47 UTC, AlexNovicov requested changes

2022-03-15 11:47 UTC, AlexNovicov commented on src/Jobs/GenerateReport.php
> +        }
Это и так логируется. Прочитай внимательно описание задачи. Я не зря указал, что нужно сделать в кроне проверку. Сейчас в задаче подробнее опишу

2022-03-15 14:54 UTC, M9snikFeed commented
Переделал

2022-03-16 07:10 UTC, AlexNovicov requested changes
В пакетах используем английский язык для аннотаций и т.д. Коммиты тоже нужно на латинице называть

2022-03-16 07:10 UTC, AlexNovicov commented on src/Repositories/Report.php
> +    public function WriteToLogErrorsReports()
Первая буква в названии строчная должна быть

2022-03-16 07:10 UTC, AlexNovicov commented on src/Repositories/Report.php
> +        ])->toArray();
Это неверно. На выполнении нас интересуют те, что выполняются уже более 3-х часов. 

Нужно еще добавить EXECUTING_STATUS, это тоже статус на выполнении

2022-03-16 07:10 UTC, AlexNovicov commented on src/Repositories/Report.php
> +    }
В репозитории не должно быть бизнес логики

2022-03-16 09:54 UTC, M9snikFeed commented
Поправил

2022-03-16 10:06 UTC, AlexNovicov requested changes

2022-03-16 10:06 UTC, AlexNovicov commented on src/Repositories/Report.php
> +        ])->toArray();
Так эти отчеты каждый час будут в лог сыпаться, а нужно один раз сообщить о них

2022-03-22 10:23 UTC, AlexNovicov requested changes

2022-03-22 10:23 UTC, AlexNovicov commented on src/Base/Report/Report.php
> +        foreach ($reports as $report) {
Не хватает проверки на пустоту $reports

2022-03-22 10:23 UTC, AlexNovicov commented on src/Base/Report/Report.php
> +        $this->report_repository->setLoggedTrueLatestReportsError();
Так не делается, нужно использовать ограничение по времени в выборке, т.е. задача выполняется раз в час и в выборке отчетов берутся отчеты за последний час (те что попадают под условия в этот последний час)

2022-03-22 10:23 UTC, AlexNovicov commented on src/Repositories/Report.php
> +        ])->toArray();
Вот здесь нужно дополнить временные рамки

2022-03-22 10:23 UTC, AlexNovicov commented on src/Repositories/Report.php
> +    }
Убрать

2022-03-22 11:37 UTC, M9snikFeed commented
Поправил

2022-03-22 12:55 UTC, AlexNovicov requested changes

2022-03-22 12:55 UTC, AlexNovicov commented on src/Jobs/WriteToLogErrorsReports.php
> +        $report->writeToLogErrorsReports($this->delay->h);
Что это $this->delay->h?

2022-03-22 12:55 UTC, AlexNovicov commented on src/Repositories/Report.php
> +        ])->toArray();
Вот что здесь должно быть:
```
'created_at' => [
    '$gte' => now()->subHour(4)->toDateString(),
    '$lt' => now()->subHour(3)->toDateString()
]
```

2022-03-23 10:16 UTC, AlexNovicov requested changes

2022-03-23 10:16 UTC, AlexNovicov commented on src/Repositories/Report.php
> +        ])->toArray();
Я писал, что отчет может генерироваться несколько часов. С таким условием только о части ошибок будет сообщаться, а нужно обо всех. Плюс убери $hours, просто числом задавай как ниже

2022-03-23 11:55 UTC, AlexNovicov approved these changes

2022-03-23 11:55 UTC, merged